services:
  strapi:
    container_name: strapi-woopear # vous pouvez modifier
    image: strapi/strapi # si vous changer la version il faudra peut etre apporter des modifications à ce document
    env_file:
      - ./strapi/.env
    environment:
      DATABASE_CLIENT: mysql # nom de la base de données utilisé
      DATABASE_HOST: ${DATABASE_HOST} # service mysql
      DATABASE_PORT: ${DATABASE_PORT} # port de la BDD
      DATABASE_NAME: ${DATABASE_NAME} # à renseigner dans votre .env
      DATABASE_USERNAME: ${DATABASE_USERNAME} # à renseigner dans votre .env
      DATABASE_PASSWORD: ${DATABASE_PASSWORD} # à renseigner dans votre .env
      DATABASE_SSL: ${DATABASE_SSL} # à modifier pour la production
    user: 1000:1000 # vous donne les droits sur le dossier strapi
    ports:
      - '1337:1337' # vous pouvez le modifier
    networks:
      - woopear-network # vous pouvez le modifier (attention il est relier à tous les services il faudra egalement le modifier la bas)
    volumes:
      - ./strapi:/srv/app:rw # volume en lecture/écriture

  sveltekit:
    container_name: sveltekit-woopear # vous pouvez modifier
    image: sveltekit-woopear # vous pouvez modifier
    restart: on-failure
    build:
      context: .
      dockerfile: ./dockerfile.front
    command: npm run dev -- --host 0.0.0.0
    ports:
      - '3000:3000' # vous pouvez modifier la premiere valeur (dans un environement wsl, il faudra modifier votre svelte.config.js)
      - '24680:24680' # vous pouvez modifier la premiere valeur (mais il faudra modifier votre svelte.config.js)
    networks:
      - woopear-network # vous pouvez le modifier (attention il est relier à tous les services il faudra egalement le modifier la bas)
    volumes:
      - ./sveltekit:/front # modifier seulement si vous savez quoi faire
      - ./sveltekit/node_modules:/front/node_modules # modifier seulement si vous savez quoi faire
      - ./sveltekit/.svelte-kit:/front/.svelte-kit # modifier seulement si vous savez quoi faire

networks:
  woopear-network: # si vous avez changer le nom de votre network modifier également le nom ici
    driver: bridge
    external: true

# si vous avez modifier les volumes modifier les aussi ici
volumes:
  strapi:
  sveltekit:
