// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCk3EsBMGuKen3ReU88chxg7tb_7ogS0Gw',
    appId: '1:993782046139:web:09ef71b8025eca246ef89e',
    messagingSenderId: '993782046139',
    projectId: 'woopear-24a22',
    authDomain: 'woopear-24a22.firebaseapp.com',
    storageBucket: 'woopear-24a22.appspot.com',
    measurementId: 'G-LZFR8W5F8H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXD246TwY9-wJmjBxJAHEZ2wvzOEWgU6k',
    appId: '1:993782046139:android:8692ff8d3fe807e26ef89e',
    messagingSenderId: '993782046139',
    projectId: 'woopear-24a22',
    storageBucket: 'woopear-24a22.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCI7B0HdMxRFAmDVIKg-gmrHEHrzsuwuvw',
    appId: '1:993782046139:ios:da28feae0ee80de06ef89e',
    messagingSenderId: '993782046139',
    projectId: 'woopear-24a22',
    storageBucket: 'woopear-24a22.appspot.com',
    iosClientId: '993782046139-k71ac5bk2vc35tevh24d6p28hrup3hsq.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
